name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: deploy/images/Dockerfile_controller
          dockerfile: deploy/images/Dockerfile_extender

  golangci:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
          args: --enable=golint

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet -v ./...

    - name: Test
      run: go test -v ./...
